project:
  type: book

book:
  title: "Solution of Exercises in Forecasting: Principles and Practice (3rd Ed)"
  author: "Shafayet Khan Shafee"
  date: last-modified
  date-format: long
  chapters:
    - index.qmd
    - ch2.qmd

format:
  html:
    theme: cosmo
execute: 
  warning: false



